### ISSUE TITLE
Hex support

### ISSUE THREAD

**Issue by EndrII** [faheel/BigInt#44] opened 2019-05-29 15:00 UTC
how to create bigInt object from hexString ?
example :
i have 512 bit number b hex
``` cpp
std::string i = "66676466FFFFFFF6676466676466676466677a7863787a637a783635343635343634323334323334323334323335333435333134"

BigInt a(i);
a += randomNumber;
string hexVar = a.toHex();

```
i want create bigInt object from this, and export this object to hex

**Comment by faheel** [comment] 2019-06-01 18:22
This functionality doesn't exist yet but has been requested earlier in issue #37, and seems like it would be useful for some use cases.

I'm closing this issue as this is a duplicate of issue #37, but feel free to follow up there.

**Closed by faheel** 2019-06-01 18:22 UTC
Labels: duplicate, enhancement
